name: Docker Build and Test Meraxes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t meraxes-builder .

      - name: Run compiled binary using input file
        run: docker run --rm meraxes-builder ./build/meraxes input/params/simulations/Genesis_L210_N4320.par
